// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Lab_A.Abstraction.IModels;

public interface IStatus
{
    public int StatusId { get; set; }
    
    public string StatusName { get; set; }

    public ICollection<IBiomaterialDelivery> BiomaterialDeliveries { get; set; }

    public ICollection<IClientOrder> ClientOrders { get; set; }

    public ICollection<IInventoryDelivery> InventoryDeliveries { get; set; }

    public ICollection<IInventoryOrder> InventoryOrders { get; set; }
}