// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Lab_A.Abstraction.IModels;
using Microsoft.EntityFrameworkCore;

namespace Lab_A.DAL.Models;

[Table("AnalysisCenter")]
public partial class AnalysisCenter : IAnalysisCenter
{
    [Key]
    [Column("analysis_center_id")]
    public int AnalysisCenterId { get; set; }

    [Column("city_id")]
    public int CityId { get; set; }

    [Column("address")]
    [StringLength(255)]
    [Unicode(false)]
    public string Address { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDatetime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDatetime { get; set; }

    [InverseProperty("AnalysisCenter")]
    public virtual ICollection<AnalysisResult> AnalysisResults { get; set; } = new List<AnalysisResult>();

    [InverseProperty("AnalysisCenter")]
    public virtual ICollection<BiomaterialDelivery> BiomaterialDeliveries { get; set; } = new List<BiomaterialDelivery>();

    [ForeignKey("CityId")]
    [InverseProperty("AnalysisCenters")]
    public virtual City City { get; set; }

    ICollection<IAnalysisResult> IAnalysisCenter.AnalysisResults
    {
        get => AnalysisResults.Cast<IAnalysisResult>().ToList();
        set => AnalysisResults = value.Cast<AnalysisResult>().ToList();
    }

    ICollection<IBiomaterialDelivery> IAnalysisCenter.BiomaterialDeliveries
    {
        get => BiomaterialDeliveries.Cast<IBiomaterialDelivery>().ToList();
        set => BiomaterialDeliveries = value.Cast<BiomaterialDelivery>().ToList();
    }

    ICity IAnalysisCenter.City
    {
        get => City;
        set => City = (City)value;
    }
}