// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Lab_A.Abstraction.IModels;
using Microsoft.EntityFrameworkCore;

namespace Lab_A.DAL.Models;

[Table("AnalysisCategory")]
public partial class AnalysisCategory : IAnalysisCategory
{
    [Key]
    [Column("analysis_category_id")]
    public int AnalysisCategoryId { get; set; }

    [Column("category")]
    [StringLength(255)]
    [Unicode(false)]
    public string Category { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDatetime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDatetime { get; set; }

    [InverseProperty("Category")]
    public virtual ICollection<Analysis> Analyses { get; set; } = new List<Analysis>();

    ICollection<IAnalysis> IAnalysisCategory.Analyses
    {
        get => Analyses.Cast<IAnalysis>().ToList();
        set => Analyses = value.Cast<Analysis>().ToList();
    }
}