// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Lab_A.Abstraction.IModels;
using Microsoft.EntityFrameworkCore;

namespace Lab_A.DAL.Models;

[Table("AnalysisResult")]
public partial class AnalysisResult : IAnalysisResult
{
    [Key]
    [Column("analysis_result_id")]
    public int AnalysisResultId { get; set; }

    [Column("order_analysis_id")]
    public int? OrderAnalysisId { get; set; }

    [Column("indicator")]
    public int? Indicator { get; set; }

    [Column("execution_date", TypeName = "datetime")]
    public DateTime? ExecutionDate { get; set; }

    [Column("description", TypeName = "text")]
    public string Description { get; set; }

    [Column("analysis_center_id")]
    public int? AnalysisCenterId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDatetime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDatetime { get; set; }

    [ForeignKey("AnalysisCenterId")]
    [InverseProperty("AnalysisResults")]
    public virtual AnalysisCenter AnalysisCenter { get; set; }

    [ForeignKey("OrderAnalysisId")]
    [InverseProperty("AnalysisResults")]
    public virtual OrderAnalysis OrderAnalysis { get; set; }

    IAnalysisCenter IAnalysisResult.AnalysisCenter
    {
        get => AnalysisCenter;
        set => AnalysisCenter = (AnalysisCenter)value;
    }

    IOrderAnalysis IAnalysisResult.OrderAnalysis
    {
        get => OrderAnalysis;
        set => OrderAnalysis = (OrderAnalysis)value;
    }
}