// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Lab_A.Abstraction.IModels;
using Microsoft.EntityFrameworkCore;

namespace Lab_A.DAL.Models;

[Table("AnalysisBiomaterial")]
public partial class AnalysisBiomaterial : IAnalysisBiomaterial
{
    [Key]
    [Column("analysis_biomaterial_id")]
    public int AnalysisBiomaterialId { get; set; }

    [Column("analysis_id")]
    public int? AnalysisId { get; set; }

    [Column("biomaterial_id")]
    public int? BiomaterialId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDatetime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDatetime { get; set; }

    [ForeignKey("AnalysisId")]
    [InverseProperty("AnalysisBiomaterials")]
    public virtual Analysis Analysis { get; set; }

    [ForeignKey("BiomaterialId")]
    [InverseProperty("AnalysisBiomaterials")]
    public virtual Biomaterial Biomaterial { get; set; }

    IAnalysis IAnalysisBiomaterial.Analysis
    {
        get => Analysis ;
        set => Analysis = (Analysis)value;
    }

    IBiomaterial IAnalysisBiomaterial.Biomaterial
    {
        get =>  Biomaterial;
        set => Biomaterial = (Biomaterial)value;
    }
}