// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Lab_A.Abstraction.IModels;
using Microsoft.EntityFrameworkCore;

namespace Lab_A.DAL.Models;

[Table("Analysis")]
public partial class Analysis : IAnalysis
{
    [Key]
    [Column("analysis_id")]
    public int AnalysisId { get; set; }

    [Column("name", TypeName = "nvarchar(255)")]
    [StringLength(255)]
    public string Name { get; set; }

    [Column("category_id")]
    public int CategoryId { get; set; }

    [Column("description", TypeName = "text")]
    public string Description { get; set; }

    [Column("price")]
    public double? Price { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDatetime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDatetime { get; set; }

    [InverseProperty("Analysis")]
    public virtual ICollection<AnalysisBiomaterial> AnalysisBiomaterials { get; set; } = new List<AnalysisBiomaterial>();

    [ForeignKey("CategoryId")]
    [InverseProperty("Analyses")]
    public virtual AnalysisCategory Category { get; set; }

    [InverseProperty("Analysis")]
    public virtual ICollection<OrderAnalysis> OrderAnalyses { get; set; } = new List<OrderAnalysis>();

    IAnalysisCategory IAnalysis.Category
    {
        get => Category;
        set => Category = (AnalysisCategory)value;
    }

    ICollection<IAnalysisBiomaterial> IAnalysis.AnalysisBiomaterials
    {
        get => AnalysisBiomaterials.Cast<IAnalysisBiomaterial>().ToList();
        set => AnalysisBiomaterials = value.Cast<AnalysisBiomaterial>().ToList();
    }

    ICollection<IOrderAnalysis> IAnalysis.OrderAnalyses
    {
        get => OrderAnalyses.Cast<IOrderAnalysis>().ToList();
        set => OrderAnalyses = value.Cast<OrderAnalysis>().ToList();
    }
}