// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Lab_A.Abstraction.IModels;
using Microsoft.EntityFrameworkCore;

namespace Lab_A.DAL.Models;

[Table("BiomaterialDelivery")]
public partial class BiomaterialDelivery : IBiomaterialDelivery
{
    [Key]
    [Column("biomaterial_delivery_id")]
    public int BiomaterialDeliveryId { get; set; }

    [Column("biomaterial_collection_id")]
    public int? BiomaterialCollectionId { get; set; }

    [Column("analysis_center_id")]
    public int? AnalysisCenterId { get; set; }

    [Column("status_id")]
    public int StatusId { get; set; }

    [Column("delivery_date", TypeName = "datetime")]
    public DateTime? DeliveryDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDatetime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDatetime { get; set; }

    [ForeignKey("AnalysisCenterId")]
    [InverseProperty("BiomaterialDeliveries")]
    public virtual AnalysisCenter AnalysisCenter { get; set; }

    [ForeignKey("BiomaterialCollectionId")]
    [InverseProperty("BiomaterialDeliveries")]
    public virtual BiomaterialCollection BiomaterialCollection { get; set; }

    [ForeignKey("StatusId")]
    [InverseProperty("BiomaterialDeliveries")]
    public virtual Status Status { get; set; }

    IAnalysisCenter IBiomaterialDelivery.AnalysisCenter
    {
        get => AnalysisCenter;
        set => AnalysisCenter = (AnalysisCenter)value;
    }

    IBiomaterialCollection IBiomaterialDelivery.BiomaterialCollection
    {
        get => BiomaterialCollection;
        set => BiomaterialCollection = (BiomaterialCollection)value;
    }

    IStatus IBiomaterialDelivery.Status
    {
        get => Status;
        set => Status = (Status)value;
    }
}