// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Lab_A.Abstraction.IModels;
using Microsoft.EntityFrameworkCore;

namespace Lab_A.DAL.Models;

[Table("Biomaterial")]
public partial class Biomaterial : IBiomaterial
{
    [Key]
    [Column("biomaterial_id")]
    public int BiomaterialId { get; set; }

    [Column("biomaterial")]
    [StringLength(255)]
    [Unicode(false)]
    public string BiomaterialName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDatetime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDatetime { get; set; }

    [InverseProperty("Biomaterial")]
    public virtual ICollection<AnalysisBiomaterial> AnalysisBiomaterials { get; set; } = new List<AnalysisBiomaterial>();

    [InverseProperty("Biomaterial")]
    public virtual ICollection<BiomaterialCollection> BiomaterialCollections { get; set; } = new List<BiomaterialCollection>();

    ICollection<IAnalysisBiomaterial> IBiomaterial.AnalysisBiomaterials
    {
        get => AnalysisBiomaterials.Cast<IAnalysisBiomaterial>().ToList();
        set => AnalysisBiomaterials = value.Cast<AnalysisBiomaterial>().ToList();
    }

    ICollection<IBiomaterialCollection> IBiomaterial.BiomaterialCollections
    {
        get => BiomaterialCollections.Cast<IBiomaterialCollection>().ToList();
        set => BiomaterialCollections = value.Cast<BiomaterialCollection>().ToList();
    }
}