// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Lab_A.Abstraction.IModels;
using Microsoft.EntityFrameworkCore;

namespace Lab_A.DAL.Models;

[Table("BiomaterialCollection")]
public partial class BiomaterialCollection : IBiomaterialCollection
{
    [Key]
    [Column("biomaterial_collection_id")]
    public int BiomaterialCollectionId { get; set; }

    [Column("expiration_date", TypeName = "datetime")]
    public DateTime? ExpirationDate { get; set; }

    [Column("volume")]
    public double? Volume { get; set; }

    [Column("collection_date")]
    public DateOnly? CollectionDate { get; set; }

    [Column("biomaterial_id")]
    public int? BiomaterialId { get; set; }

    [Column("client_order_id")]
    public int? ClientOrderId { get; set; }

    [Column("inventory_in_laboratory_id")]
    public int? InventoryInLaboratoryId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDatetime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDatetime { get; set; }

    [ForeignKey("BiomaterialId")]
    [InverseProperty("BiomaterialCollections")]
    public virtual Biomaterial Biomaterial { get; set; }

    [InverseProperty("BiomaterialCollection")]
    public virtual ICollection<BiomaterialDelivery> BiomaterialDeliveries { get; set; } = new List<BiomaterialDelivery>();

    [ForeignKey("ClientOrderId")]
    [InverseProperty("BiomaterialCollections")]
    public virtual ClientOrder ClientOrder { get; set; }

    [ForeignKey("InventoryInLaboratoryId")]
    [InverseProperty("BiomaterialCollections")]
    public virtual InventoryInLaboratory InventoryInLaboratory { get; set; }

    IBiomaterial IBiomaterialCollection.Biomaterial
    {
        get => Biomaterial;
        set => Biomaterial = (Biomaterial)value;
    }

    ICollection<IBiomaterialDelivery> IBiomaterialCollection.BiomaterialDeliveries
    {
        get => BiomaterialDeliveries.Cast<IBiomaterialDelivery>().ToList();
        set => BiomaterialDeliveries = value.Cast<BiomaterialDelivery>().ToList();
    }

    IClientOrder IBiomaterialCollection.ClientOrder
    {
        get => ClientOrder;
        set => ClientOrder = (ClientOrder)value;
    }

    IInventoryInLaboratory IBiomaterialCollection.InventoryInLaboratory
    {
        get => InventoryInLaboratory;
        set => InventoryInLaboratory = (InventoryInLaboratory)value;
    }
}