// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Lab_A.Abstraction.IModels;
using Microsoft.EntityFrameworkCore;

namespace Lab_A.DAL.Models;

[Table("ClientOrder")]
public partial class ClientOrder : IClientOrder
{
    [Key]
    [Column("client_order_id")]
    public int ClientOrderId { get; set; }

    [Column("number")]
    public int? Number { get; set; }

    [Column("status_id")]
    public int StatusId { get; set; }

    [Column("employee_id")]
    public int? EmployeeId { get; set; }

    [Column("client_id")]
    public int? ClientId { get; set; }

    [Column("biomaterial_collection_date", TypeName = "datetime")]
    public DateTime? BiomaterialCollectionDate { get; set; }

    [Column("fullprice")]
    public double? Fullprice { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDatetime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDatetime { get; set; }

    [InverseProperty("ClientOrder")]
    public virtual ICollection<BiomaterialCollection> BiomaterialCollections { get; set; } = new List<BiomaterialCollection>();

    [ForeignKey("ClientId")]
    [InverseProperty("ClientOrders")]
    public virtual Client Client { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("ClientOrders")]
    public virtual Employee Employee { get; set; }

    [InverseProperty("ClientOrder")]
    public virtual ICollection<OrderAnalysis> OrderAnalyses { get; set; } = new List<OrderAnalysis>();

    [ForeignKey("StatusId")]
    [InverseProperty("ClientOrders")]
    public virtual Status Status { get; set; }

    ICollection<IBiomaterialCollection> IClientOrder.BiomaterialCollections
    {
        get => BiomaterialCollections.Cast<IBiomaterialCollection>().ToList();
        set => BiomaterialCollections = value.Cast<BiomaterialCollection>().ToList();
    }

    IClient IClientOrder.Client
    {
        get => Client;
        set => Client = (Client)value;
    }

    IEmployee IClientOrder.Employee
    {
        get => Employee;
        set => Employee = (Employee)value;
    }

    ICollection<IOrderAnalysis> IClientOrder.OrderAnalyses
    {
        get => OrderAnalyses.Cast<IOrderAnalysis>().ToList(); 
        set => OrderAnalyses = value.Cast<OrderAnalysis>().ToList();
    }

    IStatus IClientOrder.Status
    {
        get => Status;
        set => Status = (Status)value;
    }
}