// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Lab_A.Abstraction.IModels;
using Microsoft.EntityFrameworkCore;

namespace Lab_A.DAL.Models;

[Table("Client")]
public partial class Client : IClient
{
    [Key]
    [Column("client_id")]
    public int ClientId { get; set; }

    [Column("first_name")]
    [StringLength(255)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [Column("last_name")]
    [StringLength(255)]
    [Unicode(false)]
    public string LastName { get; set; }

    [Column("sex_id")]
    public int SexId { get; set; }

    [Column("birthdate")]
    public DateOnly Birthdate { get; set; }

    [Column("phone_number")]
    [StringLength(20)]
    [Unicode(false)]
    public string PhoneNumber { get; set; }

    [Column("email")]
    [StringLength(255)]
    [Unicode(false)]
    public string Email { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDatetime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDatetime { get; set; }

    [InverseProperty("Client")]
    public virtual ICollection<ClientOrder> ClientOrders { get; set; } = new List<ClientOrder>();

    [ForeignKey("SexId")]
    [InverseProperty("Clients")]
    public virtual Sex Sex { get; set; }

    ICollection<IClientOrder> IClient.ClientOrders
    {
        get => ClientOrders.Cast<IClientOrder>().ToList();
        set => ClientOrders = value.Cast<ClientOrder>().ToList();
    }

    ISex IClient.Sex
    {
        get => Sex;
        set => Sex = (Sex)value;
    }
}