// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Lab_A.Abstraction.IModels;
using Microsoft.EntityFrameworkCore;

namespace Lab_A.DAL.Models;

[Table("Day")]
public partial class Day : IDay
{
    [Key]
    [Column("day_id")]
    public int DayId { get; set; }

    [Column("day")]
    [StringLength(255)]
    [Unicode(false)]
    public string DayName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDatetime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDatetime { get; set; }

    [InverseProperty("Day")]
    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();

    ICollection<ISchedule> IDay.Schedules
    {
        get => Schedules.Cast<ISchedule>().ToList();
        set => Schedules = value.Cast<Schedule>().ToList();
    }
}