// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Lab_A.Abstraction.IModels;
using Microsoft.EntityFrameworkCore;

namespace Lab_A.DAL.Models;

[Table("InventoryOrder")]
public partial class InventoryOrder : IInventoryOrder
{
    [Key]
    [Column("inventory_order_id")]
    public int InventoryOrderId { get; set; }

    [Column("number")]
    public int? Number { get; set; }

    [Column("supplier_id")]
    public int? SupplierId { get; set; }

    [Column("status_id")]
    public int StatusId { get; set; }

    [Column("fullprice")]
    public double? Fullprice { get; set; }

    [Column("order_date", TypeName = "datetime")]
    public DateTime? OrderDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDatetime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDatetime { get; set; }

    [InverseProperty("InventoryOrder")]
    public virtual ICollection<InventoryInOrder> InventoryInOrders { get; set; } = new List<InventoryInOrder>();

    [ForeignKey("StatusId")]
    [InverseProperty("InventoryOrders")]
    public virtual Status Status { get; set; }

    [ForeignKey("SupplierId")]
    [InverseProperty("InventoryOrders")]
    public virtual Supplier Supplier { get; set; }

    ICollection<IInventoryInOrder> IInventoryOrder.InventoryInOrders
    {
        get => InventoryInOrders.Cast<IInventoryInOrder>().ToList();
        set => InventoryInOrders = value.Cast<InventoryInOrder>().ToList();
    }

    IStatus IInventoryOrder.Status
    {
        get => Status;
        set => Status = value as Status;
    }

    ISupplier IInventoryOrder.Supplier
    {
        get => Supplier;
        set => Supplier = value as Supplier;
    }
}