// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Lab_A.Abstraction.IModels;
using Microsoft.EntityFrameworkCore;

namespace Lab_A.DAL.Models;

[Table("InventoryDelivery")]
public partial class InventoryDelivery : IInventoryDelivery
{
    [Key]
    [Column("inventory_delivery_id")]
    public int InventoryDeliveryId { get; set; }

    [Column("quantity")]
    public int? Quantity { get; set; }

    [Column("delivery_date", TypeName = "datetime")]
    public DateTime? DeliveryDate { get; set; }

    [Column("status_id")]
    public int StatusId { get; set; }

    [Column("inventory_in_laboratory_id")]
    public int? InventoryInLaboratoryId { get; set; }

    [Column("inventory_in_order_id")]
    public int? InventoryInOrderId { get; set; }

    [Column("expiration_date", TypeName = "datetime")]
    public DateTime? ExpirationDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDatetime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDatetime { get; set; }

    [ForeignKey("InventoryInLaboratoryId")]
    [InverseProperty("InventoryDeliveries")]
    public virtual InventoryInLaboratory InventoryInLaboratory { get; set; }

    [ForeignKey("InventoryInOrderId")]
    [InverseProperty("InventoryDeliveries")]
    public virtual InventoryInOrder InventoryInOrder { get; set; }

    [ForeignKey("StatusId")]
    [InverseProperty("InventoryDeliveries")]
    public virtual Status Status { get; set; }

    IInventoryInLaboratory IInventoryDelivery.InventoryInLaboratory
    {
        get => InventoryInLaboratory;
        set => InventoryInLaboratory = (InventoryInLaboratory)value;
    }

    IInventoryInOrder IInventoryDelivery.InventoryInOrder
    {
        get => InventoryInOrder;
        set => InventoryInOrder = (InventoryInOrder)value;
    }

    IStatus IInventoryDelivery.Status
    {
        get => Status;
        set => Status = (Status)value;
    }
}