// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Lab_A.Abstraction.IModels;
using Microsoft.EntityFrameworkCore;

namespace Lab_A.DAL.Models;

[Table("InventoryInOrder")]
public partial class InventoryInOrder : IInventoryInOrder
{
    [Key]
    [Column("inventory_in_order_id")]
    public int InventoryInOrderId { get; set; }

    [Column("price")]
    public double? Price { get; set; }

    [Column("quantity")]
    public int? Quantity { get; set; }

    [Column("inventory_id")]
    public int? InventoryId { get; set; }

    [Column("inventory_order_id")]
    public int? InventoryOrderId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDatetime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDatetime { get; set; }

    [ForeignKey("InventoryId")]
    [InverseProperty("InventoryInOrders")]
    public virtual Inventory Inventory { get; set; }

    [InverseProperty("InventoryInOrder")]
    public virtual ICollection<InventoryDelivery> InventoryDeliveries { get; set; } = new List<InventoryDelivery>();

    [ForeignKey("InventoryOrderId")]
    [InverseProperty("InventoryInOrders")]
    public virtual InventoryOrder InventoryOrder { get; set; }

    IInventory IInventoryInOrder.Inventory
    {
        get => Inventory; 
        set => Inventory = (Inventory)value;
    }

    ICollection<IInventoryDelivery> IInventoryInOrder.InventoryDeliveries
    {
        get => InventoryDeliveries.Cast<IInventoryDelivery>().ToList();
        set => InventoryDeliveries = value.Cast<InventoryDelivery>().ToList();
    }

    IInventoryOrder IInventoryInOrder.InventoryOrder
    {
        get => InventoryOrder;
        set => InventoryOrder = (InventoryOrder)value;
    }
}