// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Lab_A.Abstraction.IModels;

namespace Lab_A.DAL.Models;

[Table("Inventory")]
public partial class Inventory : IInventory
{
    [Key]
    [Column("inventory_id")]
    public int InventoryId { get; set; }

    [Column("inventory_name", TypeName = "nvarchar(255)")]
    [StringLength(255)]
    public string InventoryName { get; set; }

    [Column("price")]
    public double? Price { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDatetime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDatetime { get; set; }

    [InverseProperty("Inventory")]
    public virtual ICollection<InventoryInLaboratory> InventoryInLaboratories { get; set; } = new List<InventoryInLaboratory>();

    [InverseProperty("Inventory")]
    public virtual ICollection<InventoryInOrder> InventoryInOrders { get; set; } = new List<InventoryInOrder>();

    ICollection<IInventoryInLaboratory> IInventory.InventoryInLaboratories
    {
        get => InventoryInLaboratories.Cast<IInventoryInLaboratory>().ToList();
        set => InventoryInLaboratories = value.Cast<InventoryInLaboratory>().ToList();
    }

    ICollection<IInventoryInOrder> IInventory.InventoryInOrders
    {
        get => InventoryInOrders.Cast<IInventoryInOrder>().ToList();
        set => InventoryInOrders = value.Cast<InventoryInOrder>().ToList();
    }
}