// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Lab_A.Abstraction.IModels;
using Microsoft.EntityFrameworkCore;

namespace Lab_A.DAL.Models;

[Table("LaboratorySchedule")]
public partial class LaboratorySchedule : ILaboratorySchedule
{
    [Key]
    [Column("laboratory_schedule_id")]
    public int LaboratoryScheduleId { get; set; }

    [Column("laboratory_id")]
    public int? LaboratoryId { get; set; }

    [Column("schedule_id")]
    public int? ScheduleId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDatetime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDatetime { get; set; }

    [ForeignKey("LaboratoryId")]
    [InverseProperty("LaboratorySchedules")]
    public virtual Laboratory Laboratory { get; set; }

    [ForeignKey("ScheduleId")]
    [InverseProperty("LaboratorySchedules")]
    public virtual Schedule Schedule { get; set; }

    ILaboratory ILaboratorySchedule.Laboratory
    {
        get => Laboratory;
        set => Laboratory = (Laboratory)value;
    }

    ISchedule ILaboratorySchedule.Schedule
    {
        get => Schedule;
        set => Schedule = (Schedule)value;
    }
}