// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Lab_A.Abstraction.IModels;
using Microsoft.EntityFrameworkCore;

namespace Lab_A.DAL.Models;

[Table("Position")]
public partial class Position : IPosition
{
    [Key]
    [Column("position_id")]
    public int PositionId { get; set; }

    [Column("position", TypeName = "nvarchar(255)")]
    [StringLength(255)]
    public string PositionName{ get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDatetime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDatetime { get; set; }

    [InverseProperty("Position")]
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    ICollection<IEmployee> IPosition.Employees
    {
        get => Employees.Cast<IEmployee>().ToList();
        set => Employees = value.Cast<Employee>().ToList();
    }
}