// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using Lab_A.Abstraction.IModels;
using Microsoft.EntityFrameworkCore;

namespace Lab_A.DAL.Models;

[Table("Schedule")]
public partial class Schedule : ISchedule
{
    [Key]
    [Column("schedule_id")]
    public int ScheduleId { get; set; }

    [Column("day_id")]
    public int DayId { get; set; }

    [Column("start_time")]
    public TimeOnly? StartTime { get; set; }

    [Column("end_time")]
    public TimeOnly? EndTime { get; set; }

    [Column("collection_end_time")]
    public TimeOnly? CollectionEndTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDatetime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDatetime { get; set; }

    [ForeignKey("DayId")]
    [InverseProperty("Schedules")]
    public virtual Day Day { get; set; }

    [InverseProperty("Schedule")]
    public virtual ICollection<LaboratorySchedule> LaboratorySchedules { get; set; } = new List<LaboratorySchedule>();

    IDay ISchedule.Day
    {
        get => Day;
        set => Day = (Day)value;
    }

    ICollection<ILaboratorySchedule> ISchedule.LaboratorySchedules
    {
        get => LaboratorySchedules.Cast<ILaboratorySchedule>().ToList();
        set => LaboratorySchedules = value.Cast<LaboratorySchedule>().ToList();
    }
}