// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Lab_A.Abstraction.IModels;
using Microsoft.EntityFrameworkCore;

namespace Lab_A.DAL.Models;

[Table("Sex")]
public partial class Sex : ISex
{
    [Key]
    [Column("sex_id")]
    public int SexId { get; set; }

    [Column("sex", TypeName = "nvarchar(10)")]
    [StringLength(10)]
    public string SexName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDatetime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDatetime { get; set; }

    [InverseProperty("Sex")]
    public virtual ICollection<Client> Clients { get; set; } = new List<Client>();

    ICollection<IClient> ISex.Clients
    {
        get => Clients.Cast<IClient>().ToList();
        set => Clients = value.Cast<Client>().ToList();
    }
}