// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Lab_A.Abstraction.IModels;
using Microsoft.EntityFrameworkCore;

namespace Lab_A.DAL.Models;

[Table("Supplier")]
public partial class Supplier : ISupplier
{
    [Key]
    [Column("supplier_id")]
    public int SupplierId { get; set; }

    [Column("name", TypeName = "nvarchar(255)")]
    [StringLength(255)]
    public string Name { get; set; }

    [Column("email")]
    [StringLength(255)]
    public string Email { get; set; }

    [Column("phone_number", TypeName = "nvarchar(50)")]
    [StringLength(50)]
    [Unicode(false)]
    public string PhoneNumber { get; set; }

    [Column("license", TypeName = "nvarchar(255)")]
    [StringLength(255)]
    public string License { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDatetime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDatetime { get; set; }

    [InverseProperty("Supplier")]
    public virtual ICollection<InventoryOrder> InventoryOrders { get; set; } = new List<InventoryOrder>();

    ICollection<IInventoryOrder> ISupplier.InventoryOrders
    {
        get => InventoryOrders.Cast<IInventoryOrder>().ToList();
        set => InventoryOrders = (ICollection<InventoryOrder>)value;
    }
}